layout_spectrum: 0.1134894
typography_spectrum: 0.4165668
color:
  saturation: 0.4981087
  lightness: 0.4933399
  brandStrength: 0.6611775
  rhythmicContrast: 0.1268177
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: BarsikAD
